version: '3'

services:
  app1:
    container_name: API_1
    build: ./api
    ports:
      - 3000:3000
    environment:
      - MESSAGE=HOLA DESDE API 1

  app2:
    container_name: API_2
    build: ./api
    ports:
      - 3001:3000
    environment:
      - MESSAGE=HOLA DESDE API 2

  app3:
    container_name: API_3
    build: ./api
    ports:
      - 3002:3000
    environment:
      - MESSAGE=HOLA DESDE API 3

  db:
    container_name: postgreSQL
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB} #Variables de usuario, se encuentran en el archivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: